api_keys:
  etherscan: "PUT_ETHERSCAN_API_KEY_HERE"
  subscan: "PUT_SUBSCAN_API_KEY_HERE"
  blockfrost_project_id: "PUT_BLOCKFROST_PROJECT_ID_HERE"

wallet_addresses:
  bitcoin:
    - "bc1..."
  litecoin:
    - "ltc1..."
  ethereum:
    - "0x..."
  polkadot:
    - "1..."
  cardano:
    - "addr1..."
